# processout.exceptions.notfoundexception

class NotFoundException(Exception):
    pass